services:
  sumireko:
    container_name: "sumireko"
    image: "grazen/sumireko"
    ports:
      - "8000:8000"
    environment:
      PGHOST: "postgres"
      PGPORT: "5432"
      PGDATABASE: "postgres"
      PGUSER: "postgres"
      PGPASSWORD: "123"
    depends_on:
      - "postgres"
    volumes:
      - "./media:/app/media"

  postgres:
    container_name: "sumireko-postgres"
    image: "pgvector/pgvector:pg18"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"

  frontend:
    container_name: "sumireko-frontend"
    image: "grazen/sumireko-frontend"
    ports:
      - "3000:3000"
    depends_on:
      - "sumireko"
